# Generated by Django 4.2.9 on 2024-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_deiscription', models.TextField()),
                ('receipe_Image', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
